name: adapta-gtk-snap
version: '0.1'
architectures:
  - all
summary: "Adapta: An adaptive Gtk+ theme based on Material Design Guidelines."
description: |
  This snap contains multiple packages that are recommended for using the
  adapta theme in snaps. This includes roboto and noto sans fonts. These are
  the same fonts that are recommended when installing adapta-gtk-theme.

  In addition, this snap contains the papirus icon pack as this package
  contains useful adapta specific icons.

  This snap provides both Adapta and Adapta-Nokto themes. To see how to
  connect this snap to other packages please see the README in the source
  repository for the snap.

  Attribution
  This snap is packaged from Tista500's adapta-gtk-theme. It is licenced under a GPL2.0 licence
  and can be found here.
    https://github.com/adapta-project/adapta-gtk-theme
  This theme makes use of icons created by Sam Hewitt which are licensed under CC-SA-4.0.

  Similarly, papirus icon themes are provided by the Papirus team. It is under a GPL3.0 licence.
    https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

slots:
  gtk3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Adapta
        - $SNAP/share/themes/Adapta-Nokto

  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Papirus-Adapta
        - $SNAP/share/icons/Papirus-Adapta-Nokto

parts:
  adapta-theme:
    plugin: nil
    stage-packages:
      - adapta-gtk-theme
      - fonts-roboto-hinted
      - fonts-noto-hinted
      - fonts-noto-mono
      - papirus-icon-theme
    build-packages:
      - gtk-update-icon-cache
    install: |
      set -eux
      snapcraftctl build
      for dir in $SNAPCRAFT_PART_INSTALL/usr/share/icons/*/; do
        if [ -f $dir/index.theme ]; then
          gtk-update-icon-cache -q $dir
        fi
      done
    organize:
      usr/share/themes: share/themes
      usr/share/icons: share/icons
    stage:
      - share/icons/Papirus-Adapta
      - share/icons/Papirus-Adapta-Nokto
      - share/themes/*/gtk-3*
